{
 "title": "Duplicati",
 "time": { "from": "now/M", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "BackupName",
    "query": "Pictures Recent, Pictures, Documents,  Movies, Music, Duplicati Databases,test\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Uploaded",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downloaded",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "Downloaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last(\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(last) FROM (SELECT last(\"Examined\") FROM \"bytes\" GROUP BY \"BackupName\")",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(last) FROM (SELECT last(\"Known\") FROM \"bytes\" GROUP BY \"BackupName\")\n",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$BackupName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "BackupName" },
  {
   "title": "Source files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "examined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "deleted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "times",
     "query": "SELECT mean(\"Duration\") FROM \"Backup\" WHERE (\"BackupName\" = 'Documents') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Known\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Examined\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "versions",
     "measurement": "files",
     "query": "SELECT \"ListCount\" FROM \"files\" WHERE (\"BackupName\" =~ /^$BackupName$/) ",
     "select": [
      [
       { "params": [ "ListCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last (\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  { "title": "$BackupName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Source files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "examined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "deleted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "times",
     "query": "SELECT mean(\"Duration\") FROM \"Backup\" WHERE (\"BackupName\" = 'Documents') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Known\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Examined\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "versions",
     "measurement": "files",
     "query": "SELECT \"ListCount\" FROM \"files\" WHERE (\"BackupName\" =~ /^$BackupName$/) ",
     "select": [
      [
       { "params": [ "ListCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last (\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  { "title": "$BackupName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Source files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "examined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "deleted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "times",
     "query": "SELECT mean(\"Duration\") FROM \"Backup\" WHERE (\"BackupName\" = 'Documents') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Known\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Examined\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "versions",
     "measurement": "files",
     "query": "SELECT \"ListCount\" FROM \"files\" WHERE (\"BackupName\" =~ /^$BackupName$/) ",
     "select": [
      [
       { "params": [ "ListCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last (\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  { "title": "$BackupName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Source files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "examined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "deleted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "times",
     "query": "SELECT mean(\"Duration\") FROM \"Backup\" WHERE (\"BackupName\" = 'Documents') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Known\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Examined\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "versions",
     "measurement": "files",
     "query": "SELECT \"ListCount\" FROM \"files\" WHERE (\"BackupName\" =~ /^$BackupName$/) ",
     "select": [
      [
       { "params": [ "ListCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last (\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  { "title": "$BackupName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Source files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "examined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "deleted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "times",
     "query": "SELECT mean(\"Duration\") FROM \"Backup\" WHERE (\"BackupName\" = 'Documents') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Known\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Examined\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "versions",
     "measurement": "files",
     "query": "SELECT \"ListCount\" FROM \"files\" WHERE (\"BackupName\" =~ /^$BackupName$/) ",
     "select": [
      [
       { "params": [ "ListCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last (\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  { "title": "$BackupName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Source files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "examined",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "deleted",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Deleted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "added",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "files",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Added" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Remote size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "total size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT mean(\"BackupSize\") FROM \"Backup\" WHERE (\"BackupName\" = 'Duplicati Database') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    },
    {
     "alias": "size added files",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "query": "SELECT sum(\"SizeOfAddedFiles\") FROM \"test\" WHERE (\"BackupName\" = 'Duplicati Databases') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(null)",
     "select": [
      [
       { "params": [ "Uploaded" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "times",
     "query": "SELECT mean(\"Duration\") FROM \"Backup\" WHERE (\"BackupName\" = 'Documents') AND $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "Duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Known\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Known" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Source Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_BackupName",
     "groupBy": [
      { "params": [ "BackupName" ], "type": "tag" }
     ],
     "measurement": "bytes",
     "query": "SELECT last(\"Examined\") FROM \"bytes\" WHERE (\"BackupName\" =~ /^$BackupName$/) GROUP BY \"BackupName\"",
     "select": [
      [
       { "params": [ "Examined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "versions",
     "measurement": "files",
     "query": "SELECT \"ListCount\" FROM \"files\" WHERE (\"BackupName\" =~ /^$BackupName$/) ",
     "select": [
      [
       { "params": [ "ListCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "BackupName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "LastBackup",
     "query": "SELECT last (\"DurationSinceLastBackup\") FROM \"LastBackup\" WHERE $timeFilter GROUP BY time($__interval), \"BackupName\" fill(previous)",
     "select": [
      [
       { "params": [ "DurationSinceLastBackup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "BackupName", "operator": "=~", "value": "/^$BackupName$/" }
     ]
    }
   ]
  }
 ]
}